version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: main-app-postgres-db
    restart: always
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: main-app-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
