"""remove upsert unique constraints

Revision ID: 09b9c8adae08
Revises: fe15d3f77f39
Create Date: 2026-03-28 22:55:31.488294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b9c8adae08'
down_revision: Union[str, Sequence[str], None] = 'fe15d3f77f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attendance_all'), 'attendance', type_='unique')
    op.drop_constraint(op.f('uq_emp_att_event_all'), 'employee_attendance_event', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_emp_att_event_all'), 'employee_attendance_event', ['emp_id', 'apply_time'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_attendance_all'), 'attendance', ['emp_id', 'att_date', 'week_day'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
