"""make identifier not unique on project table

Revision ID: 34f2f9b69d53
Revises: 177aa8278058
Create Date: 2026-02-21 22:23:15.265595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f2f9b69d53'
down_revision: Union[str, Sequence[str], None] = '177aa8278058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_identifier_key'), 'projects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('projects_identifier_key'), 'projects', ['identifier'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
