"""update the roles for the user

Revision ID: aa2790d4654b
Revises: 58ca9e733135
Create Date: 2026-02-20 13:07:53.568378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2790d4654b'
down_revision: Union[str, Sequence[str], None] = '58ca9e733135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TYPE role ADD VALUE IF NOT EXISTS 'PROJECT MANAGER'"
    )

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
