"""make id unique

Revision ID: d6cf85db945f
Revises: 09b9c8adae08
Create Date: 2026-03-28 22:57:21.314292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cf85db945f'
down_revision: Union[str, Sequence[str], None] = '09b9c8adae08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'attendance', ['id'])
    op.create_unique_constraint(None, 'employee_attendance_event', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_attendance_event', type_='unique')
    op.drop_constraint(None, 'attendance', type_='unique')
    # ### end Alembic commands ###
