"""add upsert unique constraints

Revision ID: e04a3f780673
Revises: 0684480ce9cd
Create Date: 2026-03-28 21:40:18.070540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04a3f780673'
down_revision: Union[str, Sequence[str], None] = '0684480ce9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendance_all', 'attendance', ['emp_id', 'check_in', 'check_out', 'att_date', 'week_day'])
    op.create_unique_constraint('uq_emp_att_event_all', 'employee_attendance_event', ['emp_id', 'event_id', 'apply_time', 'start_date', 'end_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_emp_att_event_all', 'employee_attendance_event', type_='unique')
    op.drop_constraint('uq_attendance_all', 'attendance', type_='unique')
    # ### end Alembic commands ###
