"""upgrade upsert unique constraints

Revision ID: fe15d3f77f39
Revises: e04a3f780673
Create Date: 2026-03-28 22:04:01.509107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe15d3f77f39'
down_revision: Union[str, Sequence[str], None] = 'e04a3f780673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attendance_all'), 'attendance', type_='unique')
    op.create_unique_constraint('uq_attendance_all', 'attendance', ['emp_id', 'att_date', 'week_day'])
    op.drop_constraint(op.f('uq_emp_att_event_all'), 'employee_attendance_event', type_='unique')
    op.create_unique_constraint('uq_emp_att_event_all', 'employee_attendance_event', ['emp_id', 'apply_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_emp_att_event_all', 'employee_attendance_event', type_='unique')
    op.create_unique_constraint(op.f('uq_emp_att_event_all'), 'employee_attendance_event', ['emp_id', 'event_id', 'apply_time', 'start_date', 'end_date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_attendance_all', 'attendance', type_='unique')
    op.create_unique_constraint(op.f('uq_attendance_all'), 'attendance', ['emp_id', 'check_in', 'check_out', 'att_date', 'week_day'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
